#!/usr/bin/env bash

set -o errexit
set -o nounset

PANTS_VERSION=0.0.21
if ! [[ -e build-support/pants-$PANTS_VERSION.pex ]]; then
  echo "Building pants.pex @ $PANTS_VERSION"
  ./build-support/pex \
    --requirement "twitter.pants==$PANTS_VERSION" \
    --entry-point twitter.pants.bin.pants_exe:main \
    -p build-support/pants-$PANTS_VERSION.pex.tmp
  mv build-support/pants-$PANTS_VERSION.pex.tmp build-support/pants-$PANTS_VERSION.pex  # 2PC
  echo "Built pants-$PANTS_VERSION.pex"
fi

exec ./build-support/pants-$PANTS_VERSION.pex "$@"
